"""crear esquema greenfield explicito

Revision ID: 0002_esquema
Revises: 0001_greenfield
"""

import sqlalchemy as sa
from alembic import op

revision = "0002_esquema"
down_revision = "0001_greenfield"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=True),
        sa.Column("actor_id", sa.String(length=32), nullable=True),
        sa.Column("accion", sa.String(length=100), nullable=False),
        sa.Column("recurso_tipo", sa.String(length=60), nullable=False),
        sa.Column("recurso_id", sa.String(length=32), nullable=True),
        sa.Column("detalle", sa.JSON(), nullable=False),
        sa.Column("ocurrido_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hash_anterior", sa.String(length=64), nullable=False),
        sa.Column("hash_evento", sa.String(length=64), nullable=False),
        sa.Column("correlacion_id", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash_evento"),
    )
    op.create_index(op.f("ix_audit_events_accion"), "audit_events", ["accion"], unique=False)
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_cliente_id"), "audit_events", ["cliente_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_correlacion_id"), "audit_events", ["correlacion_id"], unique=False
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("codigo", sa.String(length=40), nullable=False),
        sa.Column("nombre", sa.String(length=160), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("codigo", sa.String(length=60), nullable=False),
        sa.Column("permisos", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("correo", sa.String(length=255), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("hash_contrasena", sa.String(length=255), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_correo"), "users", ["correo"], unique=True)
    op.create_table(
        "agent_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("tipo", sa.String(length=40), nullable=False),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("carga", sa.JSON(), nullable=False),
        sa.Column("resultado", sa.JSON(), nullable=True),
        sa.Column("error", sa.String(length=300), nullable=True),
        sa.Column("intentos", sa.Integer(), nullable=False),
        sa.Column("max_intentos", sa.Integer(), nullable=False),
        sa.Column("disponible_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reservado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("clave_idempotencia", sa.String(length=80), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clave_idempotencia"),
    )
    op.create_index(op.f("ix_agent_jobs_cliente_id"), "agent_jobs", ["cliente_id"], unique=False)
    op.create_index(op.f("ix_agent_jobs_estado"), "agent_jobs", ["estado"], unique=False)
    op.create_table(
        "candidates",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("nombres", sa.String(length=120), nullable=False),
        sa.Column("apellidos", sa.String(length=160), nullable=False),
        sa.Column("tipo_documento", sa.String(length=20), nullable=True),
        sa.Column("documento_normalizado", sa.String(length=64), nullable=True),
        sa.Column("correo", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=40), nullable=True),
        sa.Column("fecha_nacimiento", sa.Date(), nullable=True),
        sa.Column("ubicacion", sa.String(length=160), nullable=True),
        sa.Column("fuente", sa.String(length=80), nullable=True),
        sa.Column("reclutador", sa.String(length=160), nullable=True),
        sa.Column("perfil_solicitado", sa.String(length=160), nullable=True),
        sa.Column("conocimiento_tecnico", sa.Text(), nullable=True),
        sa.Column("disponibilidad", sa.String(length=100), nullable=True),
        sa.Column("expectativa_salarial", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("ctc_rol", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("bgc_cifrado", sa.LargeBinary(), nullable=True),
        sa.Column("equifax_cifrado", sa.LargeBinary(), nullable=True),
        sa.Column("estado", sa.String(length=32), nullable=False),
        sa.Column("etiquetas", sa.JSON(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cliente_id", "documento_normalizado", name="uq_candidate_client_document"
        ),
    )
    op.create_index(
        "ix_candidate_client_email", "candidates", ["cliente_id", "correo"], unique=False
    )
    op.create_index(
        "ix_candidate_client_phone", "candidates", ["cliente_id", "telefono"], unique=False
    )
    op.create_index(op.f("ix_candidates_cliente_id"), "candidates", ["cliente_id"], unique=False)
    op.create_index(op.f("ix_candidates_estado"), "candidates", ["estado"], unique=False)
    op.create_table(
        "exclusion_reports",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("filtros", sa.JSON(), nullable=False),
        sa.Column("hash_contenido", sa.String(length=64), nullable=False),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exclusion_reports_cliente_id"), "exclusion_reports", ["cliente_id"], unique=False
    )
    op.create_table(
        "former_employee_batches",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("hash_archivo", sa.String(length=64), nullable=False),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash_archivo"),
    )
    op.create_index(
        op.f("ix_former_employee_batches_cliente_id"),
        "former_employee_batches",
        ["cliente_id"],
        unique=False,
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("hash_archivo", sa.String(length=64), nullable=False),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("clave_idempotencia", sa.String(length=80), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clave_idempotencia"),
        sa.UniqueConstraint("hash_archivo"),
    )
    op.create_index(
        op.f("ix_import_batches_cliente_id"), "import_batches", ["cliente_id"], unique=False
    )
    op.create_table(
        "job_profiles",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("titulo", sa.String(length=200), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cliente_id", "codigo", name="uq_profile_code"),
    )
    op.create_index(
        op.f("ix_job_profiles_cliente_id"), "job_profiles", ["cliente_id"], unique=False
    )
    op.create_table(
        "pilot_metric_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("valor", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unidad", sa.String(length=30), nullable=False),
        sa.Column("dimensiones", sa.JSON(), nullable=False),
        sa.Column("ocurrido_en", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pilot_metric_events_cliente_id"),
        "pilot_metric_events",
        ["cliente_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pilot_metric_events_nombre"), "pilot_metric_events", ["nombre"], unique=False
    )
    op.create_table(
        "user_client_assignments",
        sa.Column("usuario_id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["cliente_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("usuario_id", "cliente_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("usuario_id", sa.String(length=32), nullable=False),
        sa.Column("rol_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["rol_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("usuario_id", "rol_id"),
    )
    op.create_table(
        "candidate_documents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("candidato_id", sa.String(length=32), nullable=False),
        sa.Column("nombre_original", sa.String(length=255), nullable=False),
        sa.Column("tipo_mime", sa.String(length=100), nullable=False),
        sa.Column("hash_sha256", sa.String(length=64), nullable=False),
        sa.Column("ruta_almacenamiento", sa.String(length=500), nullable=False),
        sa.Column("tamano_bytes", sa.Integer(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidato_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidato_id", "hash_sha256", name="uq_document_hash"),
    )
    op.create_index(
        op.f("ix_candidate_documents_candidato_id"),
        "candidate_documents",
        ["candidato_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_documents_cliente_id"),
        "candidate_documents",
        ["cliente_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_documents_hash_sha256"),
        "candidate_documents",
        ["hash_sha256"],
        unique=False,
    )
    op.create_table(
        "candidate_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("candidato_id", sa.String(length=32), nullable=False),
        sa.Column("tipo", sa.String(length=80), nullable=False),
        sa.Column("actor_id", sa.String(length=32), nullable=False),
        sa.Column("detalle", sa.JSON(), nullable=False),
        sa.Column("ocurrido_en", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidato_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_events_candidato_id"), "candidate_events", ["candidato_id"], unique=False
    )
    op.create_table(
        "candidate_identities",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("candidato_id", sa.String(length=32), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("valor_normalizado", sa.String(length=255), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["candidato_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_identities_candidato_id"),
        "candidate_identities",
        ["candidato_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_identities_valor_normalizado"),
        "candidate_identities",
        ["valor_normalizado"],
        unique=False,
    )
    op.create_table(
        "exclusion_entries",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("reporte_id", sa.String(length=32), nullable=False),
        sa.Column("documento", sa.String(length=64), nullable=False),
        sa.Column("motivo_generico", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["reporte_id"],
            ["exclusion_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "former_employees",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("lote_id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("documento_hash", sa.String(length=64), nullable=False),
        sa.Column("elegible_reingreso", sa.Boolean(), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["former_employee_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_former_employees_cliente_id"), "former_employees", ["cliente_id"], unique=False
    )
    op.create_index(
        op.f("ix_former_employees_documento_hash"),
        "former_employees",
        ["documento_hash"],
        unique=False,
    )
    op.create_table(
        "import_rows",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("lote_id", sa.String(length=32), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("datos", sa.JSON(), nullable=False),
        sa.Column("clasificacion", sa.String(length=40), nullable=False),
        sa.Column("errores", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["import_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_rows_lote_id"), "import_rows", ["lote_id"], unique=False)
    op.create_table(
        "job_profile_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("perfil_id", sa.String(length=32), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("requisitos", sa.JSON(), nullable=False),
        sa.Column("ctc", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("publicado", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["perfil_id"],
            ["job_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("perfil_id", "numero", name="uq_profile_version"),
    )
    op.create_index(
        op.f("ix_job_profile_versions_perfil_id"),
        "job_profile_versions",
        ["perfil_id"],
        unique=False,
    )
    op.create_table(
        "workflow_checkpoints",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("trabajo_id", sa.String(length=32), nullable=False),
        sa.Column("nodo", sa.String(length=80), nullable=False),
        sa.Column("estado", sa.JSON(), nullable=False),
        sa.Column("secuencia", sa.Integer(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trabajo_id"],
            ["agent_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trabajo_id", "secuencia", name="uq_checkpoint_seq"),
    )
    op.create_index(
        op.f("ix_workflow_checkpoints_trabajo_id"),
        "workflow_checkpoints",
        ["trabajo_id"],
        unique=False,
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("candidato_id", sa.String(length=32), nullable=False),
        sa.Column("version_perfil_id", sa.String(length=32), nullable=False),
        sa.Column("fuente", sa.String(length=80), nullable=False),
        sa.Column("estado", sa.String(length=32), nullable=False),
        sa.Column("clave_idempotencia", sa.String(length=80), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidato_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_perfil_id"],
            ["job_profile_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clave_idempotencia"),
    )
    op.create_index(
        op.f("ix_applications_candidato_id"), "applications", ["candidato_id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_cliente_id"), "applications", ["cliente_id"], unique=False
    )
    op.create_index(op.f("ix_applications_estado"), "applications", ["estado"], unique=False)
    op.create_index(
        op.f("ix_applications_version_perfil_id"),
        "applications",
        ["version_perfil_id"],
        unique=False,
    )
    op.create_table(
        "document_extractions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("documento_id", sa.String(length=32), nullable=False),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("texto_sanitizado", sa.Text(), nullable=True),
        sa.Column("campos", sa.JSON(), nullable=False),
        sa.Column("referencias", sa.JSON(), nullable=False),
        sa.Column("error", sa.String(length=300), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["candidate_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evaluations",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cliente_id", sa.String(length=32), nullable=False),
        sa.Column("postulacion_id", sa.String(length=32), nullable=False),
        sa.Column("documento_id", sa.String(length=32), nullable=False),
        sa.Column("version_perfil_id", sa.String(length=32), nullable=False),
        sa.Column("puntaje_documental", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("requiere_revision", sa.Boolean(), nullable=False),
        sa.Column("modelo", sa.String(length=100), nullable=True),
        sa.Column("version_prompt", sa.String(length=40), nullable=True),
        sa.Column("simulada", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["candidate_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["postulacion_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_perfil_id"],
            ["job_profile_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluations_cliente_id"), "evaluations", ["cliente_id"], unique=False)
    op.create_table(
        "field_suggestions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("extraccion_id", sa.String(length=32), nullable=False),
        sa.Column("campo", sa.String(length=80), nullable=False),
        sa.Column("valor", sa.JSON(), nullable=False),
        sa.Column("confianza", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("fuente", sa.JSON(), nullable=False),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["extraccion_id"],
            ["document_extractions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "human_reviews",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("evaluacion_id", sa.String(length=32), nullable=False),
        sa.Column("revisor_id", sa.String(length=32), nullable=True),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("comentario", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluacion_id"],
            ["evaluations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revisor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_human_reviews_evaluacion_id"), "human_reviews", ["evaluacion_id"], unique=False
    )
    op.create_table(
        "requirement_assessments",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("evaluacion_id", sa.String(length=32), nullable=False),
        sa.Column("codigo_requisito", sa.String(length=80), nullable=False),
        sa.Column("veredicto", sa.String(length=30), nullable=False),
        sa.Column("puntaje", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("evidencia", sa.JSON(), nullable=False),
        sa.Column("explicacion", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluacion_id"],
            ["evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requirement_assessments_evaluacion_id"),
        "requirement_assessments",
        ["evaluacion_id"],
        unique=False,
    )
    op.create_table(
        "field_corrections",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("revision_id", sa.String(length=32), nullable=False),
        sa.Column("campo", sa.String(length=80), nullable=False),
        sa.Column("valor_anterior", sa.JSON(), nullable=True),
        sa.Column("valor_nuevo", sa.JSON(), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["human_reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("field_corrections")
    op.drop_index(
        op.f("ix_requirement_assessments_evaluacion_id"), table_name="requirement_assessments"
    )
    op.drop_table("requirement_assessments")
    op.drop_index(op.f("ix_human_reviews_evaluacion_id"), table_name="human_reviews")
    op.drop_table("human_reviews")
    op.drop_table("field_suggestions")
    op.drop_index(op.f("ix_evaluations_cliente_id"), table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_table("document_extractions")
    op.drop_index(op.f("ix_applications_version_perfil_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_estado"), table_name="applications")
    op.drop_index(op.f("ix_applications_cliente_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_candidato_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_workflow_checkpoints_trabajo_id"), table_name="workflow_checkpoints")
    op.drop_table("workflow_checkpoints")
    op.drop_index(op.f("ix_job_profile_versions_perfil_id"), table_name="job_profile_versions")
    op.drop_table("job_profile_versions")
    op.drop_index(op.f("ix_import_rows_lote_id"), table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_index(op.f("ix_former_employees_documento_hash"), table_name="former_employees")
    op.drop_index(op.f("ix_former_employees_cliente_id"), table_name="former_employees")
    op.drop_table("former_employees")
    op.drop_table("exclusion_entries")
    op.drop_index(
        op.f("ix_candidate_identities_valor_normalizado"), table_name="candidate_identities"
    )
    op.drop_index(op.f("ix_candidate_identities_candidato_id"), table_name="candidate_identities")
    op.drop_table("candidate_identities")
    op.drop_index(op.f("ix_candidate_events_candidato_id"), table_name="candidate_events")
    op.drop_table("candidate_events")
    op.drop_index(op.f("ix_candidate_documents_hash_sha256"), table_name="candidate_documents")
    op.drop_index(op.f("ix_candidate_documents_cliente_id"), table_name="candidate_documents")
    op.drop_index(op.f("ix_candidate_documents_candidato_id"), table_name="candidate_documents")
    op.drop_table("candidate_documents")
    op.drop_table("user_roles")
    op.drop_table("user_client_assignments")
    op.drop_index(op.f("ix_pilot_metric_events_nombre"), table_name="pilot_metric_events")
    op.drop_index(op.f("ix_pilot_metric_events_cliente_id"), table_name="pilot_metric_events")
    op.drop_table("pilot_metric_events")
    op.drop_index(op.f("ix_job_profiles_cliente_id"), table_name="job_profiles")
    op.drop_table("job_profiles")
    op.drop_index(op.f("ix_import_batches_cliente_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(
        op.f("ix_former_employee_batches_cliente_id"), table_name="former_employee_batches"
    )
    op.drop_table("former_employee_batches")
    op.drop_index(op.f("ix_exclusion_reports_cliente_id"), table_name="exclusion_reports")
    op.drop_table("exclusion_reports")
    op.drop_index(op.f("ix_candidates_estado"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_cliente_id"), table_name="candidates")
    op.drop_index("ix_candidate_client_phone", table_name="candidates")
    op.drop_index("ix_candidate_client_email", table_name="candidates")
    op.drop_table("candidates")
    op.drop_index(op.f("ix_agent_jobs_estado"), table_name="agent_jobs")
    op.drop_index(op.f("ix_agent_jobs_cliente_id"), table_name="agent_jobs")
    op.drop_table("agent_jobs")
    op.drop_index(op.f("ix_users_correo"), table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("clients")
    op.drop_index(op.f("ix_audit_events_correlacion_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_cliente_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_accion"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
